### ISSUE TITLE
Make this a downloadable ``Tool``.

### ISSUE THREAD

**Issue by pacifiquem** [abdullah-alaadine/local-git-contributions-visualizer#19]
I'm an experienced gopher and I liked this tool. As everyone can see this is a great solution but for developers who knows these stuffs of *``building``* and *``running binaries``*. The only way to make this available for everyone is to make it *``downloadable ( avoiding users to build it themselves )``* and just provide documentation of how someone can use it.

**Comment by hrtsegv** [comment]
Thank you for your feedback! 
I appreciate your suggestion. I'll create a release with pre-built binaries in just a few minutes and work on comprehensive documentation to make it even more accessible for everyone. 
Feel free to reach out if you have any more suggestions or questions. 
Your input is invaluable!

**Comment by pacifiquem** [comment]
Thank you @abdullah-alaadine incase I get any other suggestion I'll reach out.

**Comment by hrtsegv** [comment]
Thank you too! 
Feel free to reach out anytime. 
Happy coding! 😊
