### ISSUE TITLE
take folder path in cli arguments

### ISSUE THREAD

**Issue by phanirithvij** [abdullah-alaadine/local-git-contributions-visualizer#30]
`gitcs .` or `gitcs /path/to/gitdir`
or
`gitcs -dir /path/to/gitdir`

Instead of prompting.
I personally think prompts should be a last resort and find it disruptive.

**Comment by hrtsegv** [comment]
Thank you for the suggestion! 
I totally agree with you.
I'll make sure to implement this change soon.

I'll create a new flag, as you suggested the name, `-dir`, and default it to the working directory (make it optional).

**Comment by hrtsegv** [comment]
done, I named the flag `-path`, I liked it better.
again, thanks for your suggestion, and let me know if there's still something to make it better.
